"""empty message

Revision ID: 53366d9c87cf
Revises: da885a76560a
Create Date: 2019-11-05 22:11:56.173054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53366d9c87cf'
down_revision = 'da885a76560a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
