"""empty message

Revision ID: da885a76560a
Revises: 
Create Date: 2019-10-29 14:53:29.228896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da885a76560a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
                    )
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question', sa.String(), nullable=True),
                    sa.Column('answer', sa.String(), nullable=True),
                    sa.Column('category', sa.String(), nullable=True),
                    sa.Column('difficulty', sa.Integer(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f(
                        'fk_questions_category_id_categories')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('categories')
    # ### end Alembic commands ###
